name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t darshanbennur/chai-trade-05:latest .
          docker push darshanbennur/chai-trade-05:latest
          
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull darshanbennur/chai-trade-05:latest
      - name: Delete old container
        run: docker rm -f darshanbennur/chai-trade-05:latest
      - name: Run Docker Container
        run: docker run -d -p 4000:4000 --name web-server-3 darshanbennur/chai-trade-05:latest